### ISSUE TITLE
Probably want to use `cconvert` instead of `unsafe_convert`

### ISSUE THREAD

**Issue by vchuravy** [Alexander-Barth/UDUnits.jl#1]
Since you are passing it through a `ccall`, `cconvert` is the right method to extend.

https://github.com/Alexander-Barth/UDUnits.jl/blob/4873cafa474cc4e7f74e6081a2b317ef93eb556e/src/UDUnits.jl#L174

**Comment by Alexander-Barth** [comment]
Thanks a lot for your suggestion! I made the proposed change:
https://github.com/Alexander-Barth/UDUnits.jl/commit/8f32d7349b00cc273d0ffd8176ec3505545a9630
