### ISSUE TITLE
Unitful integration?

### ISSUE THREAD

**Issue by rafaqz** [Alexander-Barth/UDUnits.jl#3]
Have you thought about integration with Unitful.jl units? a UnitfulUDUnits.jl package would be amazing.

I'm thinking about automatic conversion of say NetCDF data to Unitful data.

**Comment by Alexander-Barth** [comment]
I do not have a use-case for it personally, but if somebody wants to make such a package, I am convinced that many people would find it useful!

Good luck with your new GeoArrayBase package! 
https://github.com/rafaqz/GeoArrayBase.jl/blob/master/src/GeoArrayBase.jl

Concerning NetCDF time units and calendars these is some support for it here:
https://github.com/Alexander-Barth/NCDatasets.jl/blob/master/src/CFTime.jl
https://alexander-barth.github.io/NCDatasets.jl/stable/#Time-functions-1

Oddly, the time units are not implemented in the UDUnits C library.

**Comment by rafaqz** [comment]
Ok looks like I just signed up for it. 

Strange that they dont include time, at least seconds/hours/days. 

Ive also been looking through your work on dates and calendars in NCDatasets. It would be good to abstract some of that into a package with less dependencies.

**Comment by rafaqz** [comment]
It would also be good to get your input on the GeoArrayBase package or whatever it ends up being. A lot of my motivation for that package is around keeping the spatial metadata from netcdf (that I load with NCDatasets) attached to the in-memory arrays used in simulations. So they can be accurately plotted and analysed without getting the metadata separately.
